version: 2.1

# Define reusable executors
executors:
  cypress-executor:
    docker:
      - image: cypress/browsers:latest
    working_directory: ~/repo

# Define reusable commands
commands:
  install-dependencies:
    description: "Install npm dependencies with caching"
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

  run-cypress-tests:
    description: "Run Cypress tests with specified tags"
    parameters:
      tags:
        type: string
        default: "@smoke"
      job-name:
        type: string
        default: "cypress-tests"
    steps:
      - run:
          name: Create Reports Directory
          command: |
            mkdir -p cypress/reports/cucumber-json
            mkdir -p cypress/reports/html
            mkdir -p cypress/reports/screenshots
            mkdir -p cypress/reports/videos
      - run:
          name: Run Cypress Tests - << parameters.job-name >>
          command: |
            echo "🎯 Running tests with tags: << parameters.tags >>"
            npx cypress run --e2e --spec 'cypress/integration/e2e/**/*.feature' --env TAGS='<< parameters.tags >>' || true
            npm run generate:report
          no_output_timeout: 15m
      - store_test_results:
          path: cypress/reports
      - store_artifacts:
          path: cypress/reports/html
          destination: html-report
      - store_artifacts:
          path: cypress/reports/cucumber-json
          destination: json-reports
      - store_artifacts:
          path: cypress/reports/test-summary.json
          destination: test-summary
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots
      - store_artifacts:
          path: cypress/videos
          destination: videos

# Define jobs
jobs:
  # Generic test execution job - accepts any tags
  run-tests:
    executor: cypress-executor
    parameters:
      tags:
        type: string
        default: "@smoke"
      job-name:
        type: string
        default: "Tests"
    steps:
      - checkout
      - install-dependencies
      - run-cypress-tests:
          tags: << parameters.tags >>
          job-name: << parameters.job-name >>

# Define workflows
workflows:
  version: 2

  # Manual trigger workflow - can be triggered with parameters
  manual-testing:
    when:
      equal: [api, << pipeline.trigger_source >>]
    jobs:
      - run-tests:
          name: "Manual Testing"
          tags: << pipeline.parameters.test_tags >>
          job-name: "Manual (<< pipeline.parameters.test_tags >>)"

  # Nightly regression workflow - runs every night at 2 AM UTC
  nightly-regression:
    triggers:
      - schedule:
          cron: "0 2 * * *" # 2 AM UTC every day
          filters:
            branches:
              only:
                - main
                - master
    jobs:
      - run-tests:
          name: "Nightly Regression"
          tags: "@regression"
          job-name: "Nightly Regression"

  # Pull Request workflow - runs smoke tests on PRs
  pull-request-testing:
    when:
      not:
        equal: [scheduled_pipeline, << pipeline.trigger_source >>]
    jobs:
      - run-tests:
          name: "PR Smoke Tests"
          tags: "@smoke"
          job-name: "PR Smoke Tests"
          filters:
            branches:
              ignore:
                - main
                - master

  # Main branch workflow - runs comprehensive tests
  main-branch-testing:
    when:
      and:
        - not:
            equal: [scheduled_pipeline, << pipeline.trigger_source >>]
        - not:
            equal: [api, << pipeline.trigger_source >>]
    jobs:
      - run-tests:
          name: "Main Branch Regression"
          tags: "@regression"
          job-name: "Main Branch Regression"
          filters:
            branches:
              only:
                - main
                - master

# Pipeline parameters for manual triggers
parameters:
  test_tags:
    type: string
    default: "@smoke"
    description: "Cucumber tags to run (e.g., @smoke, @regression, @smoke,@search)"
